scalar Date
scalar DateTime
scalar LocalTime

type Query {
    notices(input: NoticeInput): [NoticeCategory!]!
    calendar(input: AcademicCalendarInput): AcademicCalendar!
    phonebook(input: PhonebookInput): Phonebook!
    readingRoom: [ReadingRoom!]!
    commute: [CommuteShuttleRoute!]!
}

# 공지사항 카테고리와 공지사항을 반환하는 쿼리입니다.
input NoticeInput {
    category: String
    language: String
    timestamp: DateTime
}

type NoticeCategory {
    seq: Int!
    name: String!
    notices: [Notice!]!
}

type Notice {
    seq: Int!
    title: String!
    url: String!
    userID: String!
    language: String!
    expiredAt: DateTime!
}

# 학사일정 버전, 학사일정 카테고리 및 학사일정을 반환하는 쿼리입니다.
input AcademicCalendarInput {
    category: String
    start: Date
    end: Date
}

type AcademicCalendar {
    version: String!
    categories: [AcademicCalendarCategory!]!
}

type AcademicCalendarCategory {
    seq: Int!
    name: String!
    events: [AcademicCalendarEvent!]!
}

type AcademicCalendarEvent {
    seq: Int!
    title: String!
    description: String!
    start: Date!
    end: Date!
}

# 전화부 버전, 전화부 카테고리 및 전화부 항목을 반환하는 쿼리입니다.
input PhonebookInput {
    category: String
    campus: Int
    name: String
    phone: String
}

type Phonebook {
    version: String!
    categories: [PhonebookCategory!]!
}

type PhonebookCategory {
    seq: Int!
    name: String!
    entries: [PhonebookEntry!]!
}

type PhonebookEntry {
    seq: Int!
    name: String!
    phone: String!
}

# 열람실 정보와 열람실 좌석 정보를 반환하는 쿼리입니다.
type ReadingRoom {
    seq: Int!
    name: String!
    campus: Int!
    active: Boolean!
    reservable: Boolean!
    seats: ReadingRoomSeat!
    updatedAt: DateTime!
}

type ReadingRoomSeat {
    total: Int!
    available: Int!
    active: Int!
    occupied: Int!
}

# 통학버스 노선 및 시간표를 반환하는 쿼리입니다.
type CommuteShuttleRoute {
    name: String!
    description: CommuteShuttleDescription!
    timetable: [CommuteShuttleTimetable!]!
}

type CommuteShuttleDescription {
    korean: String!
    english: String!
}

type CommuteShuttleTimetable {
    name: String!
    order: Int!
    time: LocalTime!
}